/* Basic unit test jenkins file*/

node{
	stage('Preperation'){
		build 'ci_unit_test_prep_job'
	}
	stage('Test') {
        	echo "do test task here"
	}
	stage('Result') {
		echo "do test conclusion task here"
	}
}
